version: '3'

services:
  api:
    container_name: bot-api
    build: ./bot-api
    env_file:
      - ./bot-api/.env
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3000"
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
  media-proccessor:
    container_name: media-proccessor
    build: ./media-proccessor
    env_file:
      - .env
    ports:
      - "8001:8001"
  