name: On pull request open

on:
  pull_request:
    types: [opened]

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.22.5'

            - name: Test
              run: go test -v ./...